### ISSUE TITLE
PROBLEEMIDE REGISTER

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Content-Analysis#12]
Let's collect here all the problems that need to be fixed:

- [ ] buerokratt/Content-Analysis#20
- [ ] buerokratt/Content-Analysis#23
- [ ] buerokratt/Buerokratt-Chatbot#728
- [ ] buerokratt/Buerokratt-Chatbot#738
- [ ] Include 2-3 previous questions with the question forwarded to LLM in order to improve understanding of the context
- [ ] buerokratt/Content-Analysis#22
